emsync/emsyncv2

.prettierrc.yml
package-lock.json
package.json
script/seed.js
script/seed.spec.js
server/api/users.spec.js
server/db/models/index.js
server/db/models/room.js
server/db/models/user.js
server/db/models/user.spec.js

sequelize models

---

package-lock.json
package.json
script/seed.js
server/db/models/index.js
server/db/models/queueItem.js
server/db/models/room.js

creates queueItem model and updates seeding script

---

client/components/NavBar.js
client/components/index.js
client/store/user.spec.js
script/seed.spec.js
server/api/user.js
server/api/users.spec.js
server/auth/spotify.js

- logout button now working
- only logs out users from our site - they are still logged into spotify (so if you click login again, it won't prompt you to login, will just automatically retrieve tokens)

logout working

---

client/components/SearchForm.js

Search form optimized (submit on pressEnter added)

---

client/components/ListenersList.js
client/components/RoomView.js
package-lock.json
server/socket/index.js

- users now disappear from room on disconnect

38 sockets disconnect

---

client/components/Queue.js
client/components/QueueElement.js
client/components/RoomForm.js
client/components/RoomView.js
client/components/SearchForm.js
client/components/roomSingleCard.js
server/db/models/room.js

progress made, still trying to get the submit form to work

---

client/components/RoomView.js
client/components/giphyResultsList.js
client/components/giphySearch.js
client/routes.js
client/store/giphy.js
client/store/index.js
package-lock.json
package.json
server/api/giphy.js
server/api/index.js

this is where the speedometer and the giphy stuff is -- gotta still connect giphy with teh add form, right now it has its own route

Experiment

---

client/components/RoomForm.js
client/components/RoomView.js
client/components/SpotifyWebPlayer.js
client/components/giphyResultsList.js
client/components/giphySearch.js
client/components/roomSingleCard.js
package-lock.json
package.json
server/api/rooms.js

fixed the submit bug and also added giphy

Add room fix

---

client/components/roomSingleCard.js

added a bug but just fixed it sooorrry

---

client/components/RoomView.js
client/components/SpotifyWebPlayer.js
emsync_database
server/socket/index.js

- users songs now sync when one or the other clicks 'next track'

users sync when clicking next_track

---

client/components/Queue.js
client/components/QueueElement.js
client/components/RoomView.js
client/components/SpotifyWebPlayer.js
emsync_database
server/socket/index.js

- user queues sync when adding new song
- still buggy when queues aren't ordered the same

70 queue sync

---

client/components/NavBar.js
client/components/RoomView.js
client/components/SpotifyWebPlayer.js
client/components/giphyResultsList.js
client/components/roomSingleCard.js
public/index.html
public/style.css

Aesthetics

---

client/components/QueueElement.js
public/style.css

- can delete songs from queue
- button changes color on hover

delete songs from queue

---

client/components/RoomView.js
server/api/queues.js

fixed the DJ bug

---

client/components/RoomForm.js
client/components/giphyResultsList.js
script/seed.js
server/api/rooms.js

it was a seeding problem
sorteD!?!?!?!

figured it out woooo

---

client/components/RoomForm.js
script/seed.js
server/api/rooms.js

fixes add room form bugs

---

client/components/RoomForm.js
client/components/giphyResultsList.js
client/components/giphySearch.js
public/style.css

Add ROom doesnt look terrible!!

---

client/components/Landing.js
client/components/NavBar.js
client/components/RoomForm.js
client/routes.js
public/style.css
server/auth/spotify.js
server/db/models/room.js

adds stuff to landing page

---

client/components/Loading.js
client/components/QueueElement.js
client/components/RoomView.js
client/components/RoomsList.js
client/components/SpotifyWebPlayer.js
client/components/UserHome.js
client/components/roomSingleCard.js
client/store/queue.js
public/style.css

- queue now more robust on handling empty queue status

Temp branch

---

client/components/SearchForm.js
client/components/roomSingleCard.js
public/style.css
script/seed.js

done some stuff

---

client/components/SearchForm.js
public/style.css

warning fix
